name: Frontend Code Upload to S3

on:
  workflow_dispatch:

jobs:
    frontend-upload:
        runs-on: ubuntu-24.04
        defaults:
            run:
                working-directory: "./terraform"
        permissions:
            id-token: write   # This is required for requesting the JWT
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ vars.AWS_GITHUB_ROLE_ARN }}
                role-session-name: github-actions-session
                aws-region: eu-west-2

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.11.1

            - name: Terraform Init
              run: terraform init

            - name: Get Terraform Outputs
              id: terraform
              run: |
                BUCKET_NAME=$(terraform output -raw s3_bucket_name)
                API_URL=$(terraform output -raw api_gateway_url)
                STAGE_NAME=$(terraform output -raw api_gateway_stage_name)
                echo "bucket_name=$BUCKET_NAME" >> $GITHUB_OUTPUT
                echo "api_url=$API_URL" >> $GITHUB_OUTPUT
                echo "stage_name=$STAGE_NAME" >> $GITHUB_OUTPUT

            - name: Upload to S3
              working-directory: "./frontend"
              shell: bash
              run: |
                sed -i "s|const API_BASE_URL = '';|const API_BASE_URL = '${{ steps.terraform.outputs.api_url }}';|g" index.html
                sed -i "s|const API_STAGE_NAME = '';|const API_STAGE_NAME = '${{ steps.terraform.outputs.stage_name }}';|g" index.html
                sed -i "s|const API_BASE_URL = '';|const API_BASE_URL = '${{ steps.terraform.outputs.api_url }}';|g" error.html
                aws s3 sync . "s3://${{ steps.terraform.outputs.bucket_name }}" --delete