name: Terraform Apply

on:
  workflow_dispatch:

# on:
#     push:
#         branches:
#             - dev


jobs:
    terraformapply:
        runs-on: ubuntu-24.04
        defaults:
            run:
                working-directory: "./terraform"
        permissions:
          id-token: write   # This is required for requesting the JWT
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ vars.AWS_GITHUB_ROLE_ARN }}
                role-session-name: github-actions-session
                aws-region: eu-west-2

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.11.1

            - name: Terraform Init
              run: terraform init

            - name: Terraform Apply
              run: terraform apply -auto-approve

            - name: Get Terraform Outputs
              id: terraform
              run: |
                DOMAIN_NAME=$(terraform output -raw website_domain)
                echo "domain_name=$DOMAIN_NAME" >> $GITHUB_OUTPUT

            - name: Deployment Summary
              run: |
                echo "## Infrastructure Deployment Complete" >> $GITHUB_STEP_SUMMARY
                echo "" >> $
                echo "" >> $GITHUB_STEP_SUMMARY
                echo "**CloudFront Domain:** \`${{ steps.terraform.outputs.domain_name }}\`" >> $GITHUB_STEP_SUMMARY
                echo "" >> $GITHUB_STEP_SUMMARY
                echo "### Now you need to:" >> $GITHUB_STEP_SUMMARY
                echo "1. **Deploy Frontend Code:** Run the \`Frontend Code Upload\` workflow to upload your frontend files" >> $GITHUB_STEP_SUMMARY
                echo "2. **Access Your Site:** Visit your domain once frontend is deployed" >> $GITHUB_STEP_SUMMARY
                echo "" >> $GITHUB_STEP_SUMMARY
                echo "" >> $GITHUB_STEP_SUMMARY
                echo "The frontend deployment pipeline will automatically invalidate CloudFront cache for immediate updates" >> $GITHUB_STEP_SUMMARY